version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/project1-yli3466"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "pip"
    directory: "/milestone2-yli3466"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "pip"
    directory: "/milestone3-yli3466"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/milestone3-yli3466/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

