[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
# Start permissive: focus on likely runtime errors; avoid style noise.
select = ["E9", "F63", "F7", "F82"]
line-length = 100
target-version = "py311"

